#!/bin/bash

NAME="dj_docs"                                    # Name of the application
DJANGODIR=/home/djdocs/dj_docs                    # Django project directory
SOCKFILE=$DJANGODIR/run/gunicorn.sock             # we will communicte using this unix socket
LOGDIR=$DJANGODIR/log
USER=root                                         # the user to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_WSGI_MODULE=dj_docs.wsgi                   # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../bin/activate
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Create log directory if it doesn't exist
test -d $LOGDIR || mkdir -p $LOGDIR

# Start your Django Unicorn
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE} \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
--log-file=$LOGDIR/gunicorn.log