# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polluser',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='polluser',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='polluser',
            old_name='middle_name',
            new_name='middlename',
        ),
    ]
